### ISSUE TITLE
Missed proxy configured

### ISSUE THREAD

**Issue by krismorte** [ozankaraali/InstaManager#1]
I need to configure a proxy to Instagram4J and the GUI doens't show this option.

**Comment by ozankaraali** [comment]
I added proxy settings in 1.0.9 (that I did not check if it is working or not), check if it works and give feedback if you can.

**Comment by krismorte** [comment]
I not accustomed with the intellij IDE, so the news controls doens't appear. I try to using with netbeans 8 and to run your app I need initialize this controls and call the follow method

```
sneakCheck = new JCheckBox();
aboutButton = new JButton();
 statusText = new JLabel();
$$$setupUI$$$()
```

**Comment by ozankaraali** [comment]
There is a release build that you can use.

**Comment by ozankaraali** [comment]
Since there's no feedback, I am closing this issue as solved.
